### PR TITLE
Update and Render Refactor For SDLUI_TextBox_Control

### PR DESCRIPTION
**Pull request by Noah11012**
Couldn't do the same with the list control because there are static variables within the usage function so it complicates things a bit.

### CODE REVIEW

**Comment by immortalx74** [comment]
Just tested it on Windows and seems to work perfect! I don't know if I merged the pull request correctly though.
Thanks for all the hard work!

**Comment by Noah11012** [comment]
@immortalx74 Glad to hear that my work payed off! But one question I must ask: do you notice any input lag? E.g. the amount of time between pressing the key and the actual character being rendered on screen compared previously?

**Comment by immortalx74** [comment]
No it seems as fast as before. You're on Linux right? My son just set-up a distro on my PC and I'm gonna test it there too (in case it's a Linux thing). Will report back.

**Comment by Noah11012** [comment]
@immortalx74 After I did my changes the input lag was tolerable but very much noticeable. And yeah, I'm running Linux. Manjaro to be specific.

**Comment by immortalx74** [comment]
Hmmm, just tested it (on Manjaro too) and it seems the same speed as in Windows.

I also noticed that smooth scrolling doesn't work in Linux, on List and ScrollArea controls. Also, horizontal scrolling is reversed in Linux for some reason. I guess it's an SDL thing.
BTW by smooth scrolling I mean that when you scroll and let go off the wheel (or lift your fingers off the touchpad), on Windows it keeps scrolling (decelerating) and it eventually stops.

**Comment by Noah11012** [comment]
Just tested the List and ScrollArea controls on my end. Same thing. No smooth scrolling.

**Pull request merged**
